-- // DML_Create_Spring_Security_Tables
-- Migration SQL that makes the change goes here.

CREATE TABLE USER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(64)  NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(40)  NOT NULL,
    NONEXPIRED BOOLEAN DEFAULT 1,
    NONLOCKED BOOLEAN DEFAULT 1,
    CREDSNONEXPIRED BOOLEAN DEFAULT 1,
    ENABLED BOOLEAN DEFAULT 0,
    PRIMARY KEY(ID),
    UNIQUE (USERNAME),
    UNIQUE (EMAIL)
);
-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE USER;