-- // user_has_authority
-- Migration SQL that makes the change goes here.

CREATE TABLE USER_AUTHORITY(
  USER_ID INT NOT NULL,
  AUTHORITY_ID INT NOT NULL,
  PRIMARY KEY(USER_ID, AUTHORITY_ID),
  FOREIGN KEY(USER_ID) REFERENCES USER(ID),
  FOREIGN KEY(AUTHORITY_ID) REFERENCES AUTHORITY(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE USER_AUTHORITY;