logging:
    level:
        org:
            hibernate: TRACE
server:
    port: 8082
spring:
    datasource:
        password: ''
        url: jdbc:h2:mem:lpm
        username: sa
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
            indent_output: true
    jpa:
        database: H2
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
        show-sql: true
