CREATE TABLE USER_AUTHORITY(
  LPM_USER_ID BIGINT NOT NULL ,
  AUTHORITY_ID BIGINT NOT NULL,
  CONSTRAINT PK_USER_AUTHORITY PRIMARY KEY(LPM_USER_ID, AUTHORITY_ID),
  CONSTRAINT FK_USER_AUTHORITY_USER FOREIGN KEY(LPM_USER_ID) REFERENCES LPM_USER(ID),
  CONSTRAINT FK_USER_AUTHORITY_AUTHORITY FOREIGN KEY(AUTHORITY_ID) REFERENCES AUTHORITY(ID)
);