CREATE TABLE ACTIVATION_TOKEN (
  ID          BIGSERIAL,
  LPM_USER_ID BIGINT       NOT NULL,
  TOKEN       VARCHAR(250) NOT NULL UNIQUE,
  CONSTRAINT PK_USER_ACTIVATION PRIMARY KEY (ID),
  CONSTRAINT FK_USER_ACTIVATION_USER FOREIGN KEY (LPM_USER_ID) REFERENCES LPM_USER (ID)
);