CREATE TABLE LPM_USER (
    ID BIGSERIAL,
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(64)  NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(40)  NOT NULL,
    NONEXPIRED BOOLEAN DEFAULT TRUE ,
    NONLOCKED BOOLEAN DEFAULT TRUE,
    CREDSNONEXPIRED BOOLEAN DEFAULT TRUE,
    ENABLED BOOLEAN DEFAULT FALSE,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT U_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT U_USER_EMAIL UNIQUE (EMAIL)
);